In [80]:
import pandas as pd
import numpy as np
import glob

In [81]:
# for _ in range(100):
#     print(np.random.rand())

In [82]:
# Set the path to the directory containing the CSV files
path = './results/'

compilation_path = f'{path}compilation/'

# Find all CSV files in the directory
csv_files = glob.glob(path + '/*.csv')

# Create an empty list to store the DataFrames
result_dfs = []

# Loop through the CSV files and append them to the list
for file in csv_files:
    result_df = pd.read_csv(file)
    result_dfs.append(result_df)

# Concatenate the DataFrames into a single DataFrame
df = pd.concat(result_dfs, ignore_index=True)

df = df.drop(columns=['timestamp'])

# Print the combined DataFrame
df

,approach_name,dataset_name,classifier_name,sensitive_name,samples,tot_inputs,disc_inputs,disc_rate,elapsed_time,egs
0,AEQUITAS+FairBS,census,dt,sex,1001,194295,3795,1.9532,637.176632,5.955962
1,AEQUITAS+FairBS,census,dt,sex,1001,196371,4666,2.3761,625.627353,7.458114
2,AEQUITAS+FairBS,census,dt,sex,1001,197676,3356,1.6977,630.076055,5.326341
3,AEQUITAS+FairBS,census,dt,sex,1001,196826,4002,2.0333,633.970261,6.312599
4,AEQUITAS+FairBS,census,dt,sex,1001,196787,3452,1.7542,638.930299,5.402780
...,...,...,...,...,...,...,...,...,...,...
1645,FairBS,compas,lr,race,1765,20715,1272,6.1405,300.103139,4.238543
1646,FairBS,compas,lr,race,1792,23433,1557,6.6445,300.258611,5.185530
1647,FairBS,compas,lr,race,1739,23563,1538,6.5272,300.052164,5.125775
1648,FairBS,compas,lr,race,1732,19566,648,3.3119,300.137239,2.159012
1649,FairBS,compas,lr,race,1779,18618,791,4.2486,300.139901,2.635438

In [83]:
df_selected = df[(df['approach_name'].isin(['AEQUITAS', 'FairBS', 'SDG'])) & (df['classifier_name'].isin(['dt', 'rf', 'mlp', 'lr']))]
df_selected

,approach_name,dataset_name,classifier_name,sensitive_name,samples,tot_inputs,disc_inputs,disc_rate,elapsed_time,egs
550,AEQUITAS,census,dt,sex,5,13501,785,5.8144,314.872292,2.493074
551,AEQUITAS,census,dt,sex,12,13642,1502,11.0101,304.264610,4.936493
552,AEQUITAS,census,dt,sex,9,13564,1171,8.6331,308.436557,3.796567
553,AEQUITAS,census,dt,sex,11,13517,989,7.3167,312.182261,3.168021
554,AEQUITAS,census,dt,sex,9,13454,782,5.8124,317.827462,2.460454
...,...,...,...,...,...,...,...,...,...,...
1645,FairBS,compas,lr,race,1765,20715,1272,6.1405,300.103139,4.238543
1646,FairBS,compas,lr,race,1792,23433,1557,6.6445,300.258611,5.185530
1647,FairBS,compas,lr,race,1739,23563,1538,6.5272,300.052164,5.125775
1648,FairBS,compas,lr,race,1732,19566,648,3.3119,300.137239,2.159012
1649,FairBS,compas,lr,race,1779,18618,791,4.2486,300.139901,2.635438

In [84]:
df_selected = df_selected.groupby(['approach_name', 'dataset_name', 'sensitive_name', 'classifier_name']).mean().reset_index()

# Round all numeric columns to 2 decimal places
df_selected = df_selected.round(2)

# Specify the columns you want to round to the nearest whole number
columns_to_round = ['tot_inputs', 'disc_inputs'] 
# Round the specified columns to 0 decimal places
df_selected[columns_to_round] = df_selected[columns_to_round].round(0)

df_selected

,approach_name,dataset_name,sensitive_name,classifier_name,samples,tot_inputs,disc_inputs,disc_rate,elapsed_time,egs
0,AEQUITAS,bank,age,dt,257.5,3959.0,830.0,20.87,363.44,2.29
1,AEQUITAS,bank,age,lr,4.1,3663.0,99.0,2.69,345.74,0.28
2,AEQUITAS,bank,age,mlp,173.0,4098.0,1344.0,32.57,330.53,4.07
3,AEQUITAS,bank,age,rf,340.7,3738.0,1517.0,40.16,355.27,4.24
4,AEQUITAS,bank,marital,dt,212.1,7736.0,798.0,10.30,327.94,2.43
...,...,...,...,...,...,...,...,...,...,...
83,FairBS,credit,sex,rf,919.0,121276.0,21873.0,18.04,301.20,72.63
84,FairBS,meps,SEX,dt,1442.4,161681.0,5061.0,3.13,300.78,16.83
85,FairBS,meps,SEX,lr,1307.8,130760.0,22816.0,17.42,300.86,75.83
86,FairBS,meps,SEX,mlp,1297.2,106965.0,15419.0,14.42,301.07,51.21
87,FairBS,meps,SEX,rf,1242.0,116069.0,23903.0,20.59,301.14,79.37

In [85]:
approaches = ['FairBS', 'SDG', 'AEQUITAS']
# approaches =  df_selected['approach_name'].unique()
for approach in approaches:
    df_selected[(df_selected['approach_name']==approach)].to_csv(f'{compilation_path}{approach}_results.csv', index=False)

In [86]:
# # Group by the relevant columns and calculate the mean
# grouped_df = df.groupby(['approach_name', 'dataset_name', 'sensitive_name', 'classifier_name']).mean()

# # Pivot the DataFrame so that each approach's metrics become separate columns
# pivot_df = grouped_df.unstack(level=0)

# # Flattening the multi-level columns
# pivot_df.columns = ['_'.join(col).strip() for col in pivot_df.columns.values]

# # Resetting index to bring 'dataset_name', 'sensitive_name', and 'classifier_name' back into the DataFrame
# pivot_df.reset_index(inplace=True)

# # Round all numeric columns to 2 decimal places
# pivot_df = pivot_df.round(2)

# # Save the DataFrame to a CSV file
# pivot_df.to_csv('results.csv', index=False)

# # Display the final DataFrame
# pivot_df

In [87]:
grouped_df = df_selected.groupby(['approach_name', 'dataset_name', 'sensitive_name', 'classifier_name']).mean()

# Pivot the DataFrame so that each approach's metrics become separate columns
pivot_df = grouped_df.unstack(level=0)

# Flattening the multi-level columns
pivot_df.columns = ['_'.join(col).strip() for col in pivot_df.columns.values]

# Resetting index to bring 'dataset_name', 'sensitive_name', and 'classifier_name' back into the DataFrame
pivot_df.reset_index(inplace=True)

pivot_df.to_csv(f'{compilation_path}results.csv', index=False)

# Displaying the final DataFrame
pivot_df

,dataset_name,sensitive_name,classifier_name,samples_AEQUITAS,samples_FairBS,tot_inputs_AEQUITAS,tot_inputs_FairBS,disc_inputs_AEQUITAS,disc_inputs_FairBS,disc_rate_AEQUITAS,disc_rate_FairBS,elapsed_time_AEQUITAS,elapsed_time_FairBS,egs_AEQUITAS,egs_FairBS
0,bank,age,dt,257.5,870.0,3959.0,44497.0,830.0,9877.0,20.87,22.18,363.44,304.09,2.29,32.48
1,bank,age,lr,4.1,1115.1,3663.0,25438.0,99.0,739.0,2.69,2.80,345.74,300.74,0.28,2.46
2,bank,age,mlp,173.0,955.2,4098.0,43545.0,1344.0,19917.0,32.57,45.67,330.53,303.29,4.07,65.69
3,bank,age,rf,340.7,785.8,3738.0,36002.0,1517.0,20593.0,40.16,57.17,355.27,304.43,4.24,67.64
4,bank,marital,dt,212.1,914.4,7736.0,131385.0,798.0,22228.0,10.30,16.92,327.94,301.15,2.43,73.81
5,bank,marital,lr,4.7,1116.1,7724.0,45160.0,223.0,1011.0,2.88,2.21,311.42,300.24,0.72,3.37
6,bank,marital,mlp,5.7,1123.4,6994.0,104562.0,98.0,1352.0,1.44,1.29,320.74,301.27,0.30,4.49
7,bank,marital,rf,208.0,916.7,6974.0,92282.0,2144.0,33898.0,30.59,36.73,326.27,301.52,6.54,112.43
8,census,age,dt,571.2,429.8,8072.0,50384.0,5199.0,25798.0,63.79,51.09,323.98,301.32,16.08,85.63
9,census,age,lr,57.1,943.9,5341.0,52285.0,1668.0,31024.0,30.65,59.27,321.60,301.55,5.19,102.92
10,census,age,mlp,132.7,868.3,9222.0,59201.0,6576.0,45177.0,68.98,76.23,311.57,301.23,21.25,149.96
11,census,age,rf,140.8,860.2,3700.0,36272.0,977.0,16566.0,25.90,45.59,343.48,303.66,2.86,54.55
12,census,race,dt,2.5,998.5,6213.0,79224.0,347.0,211.0,5.46,0.27,315.15,301.64,1.09,0.70
13,census,race,lr,7.6,993.4,6714.0,66636.0,326.0,1799.0,4.84,2.69,336.10,300.89,0.97,5.98
14,census,race,mlp,8.0,993.0,5971.0,62046.0,384.0,1792.0,6.38,2.89,341.14,301.45,1.13,5.95
15,census,race,rf,39.0,962.0,4543.0,52476.0,388.0,4320.0,8.33,8.23,321.75,302.01,1.19,14.30
16,census,sex,dt,10.1,990.9,13540.0,183193.0,1151.0,3041.0,8.49,1.66,309.71,300.72,3.73,10.11
17,census,sex,lr,6.0,995.0,13539.0,128513.0,700.0,14717.0,5.17,11.45,305.67,300.41,2.29,48.99
18,census,sex,mlp,30.7,970.3,12903.0,123845.0,2072.0,27810.0,15.81,22.46,310.83,300.47,6.65,92.56
19,census,sex,rf,61.9,939.1,10287.0,116287.0,1981.0,23982.0,19.05,20.62,315.45,300.68,6.28,79.76
20,compas,age,dt,543.4,1255.9,6721.0,48268.0,2418.0,15698.0,34.92,32.49,336.31,302.40,7.19,51.90
21,compas,age,lr,22.2,1764.7,5788.0,34986.0,222.0,28543.0,3.80,81.64,355.45,300.56,0.63,94.96
22,compas,age,mlp,18.0,1772.6,5055.0,31291.0,112.0,26229.0,2.23,83.84,361.90,301.27,0.31,87.07
23,compas,age,rf,230.1,1546.2,4584.0,41521.0,647.0,27884.0,14.04,67.05,397.98,302.81,1.62,92.05
24,compas,race,dt,871.1,918.4,10497.0,82574.0,5835.0,44047.0,54.93,53.32,314.72,301.88,18.58,145.91
25,compas,race,lr,7.3,1764.3,7322.0,20236.0,110.0,902.0,1.54,4.27,343.17,300.26,0.32,3.01
26,compas,race,mlp,10.6,1778.0,6167.0,12928.0,126.0,807.0,2.05,5.66,324.38,300.22,0.39,2.69
27,compas,race,rf,229.9,1539.6,6529.0,52809.0,1061.0,30110.0,16.53,57.02,368.60,301.13,2.91,99.99
28,compas,sex,dt,105.3,1680.3,17908.0,183184.0,1323.0,12946.0,7.41,7.07,311.21,300.68,4.26,43.06
29,compas,sex,lr,4.8,1770.6,16402.0,34980.0,212.0,12086.0,1.31,34.89,308.07,300.25,0.68,40.25
30,compas,sex,mlp,5.8,1775.5,14463.0,31609.0,191.0,17308.0,1.35,55.02,308.64,300.14,0.62,57.67
31,compas,sex,rf,87.5,1688.4,12102.0,102525.0,846.0,27663.0,6.96,26.99,310.03,300.91,2.74,91.93
32,credit,age,dt,83.0,918.0,3118.0,45617.0,323.0,9820.0,10.38,21.51,349.08,302.39,0.93,32.48
33,credit,age,lr,173.0,828.0,3829.0,47121.0,943.0,8356.0,24.62,17.56,374.47,302.49,2.53,27.61
34,credit,age,mlp,137.7,863.3,3633.0,38155.0,1110.0,5887.0,30.36,15.25,357.79,301.86,3.09,19.51
35,credit,age,rf,194.2,806.8,2740.0,34343.0,653.0,12381.0,23.18,36.04,374.14,304.49,1.71,40.66
36,credit,sex,dt,4.9,996.1,8427.0,169087.0,968.0,1230.0,11.39,0.73,317.57,300.88,3.03,4.09
37,credit,sex,lr,60.3,940.7,8564.0,171176.0,707.0,29888.0,8.18,17.46,320.96,300.73,2.19,99.38
38,credit,sex,mlp,13.4,987.6,7315.0,141450.0,257.0,9085.0,3.51,6.42,324.64,300.87,0.79,30.20
39,credit,sex,rf,82.0,919.0,5936.0,121276.0,633.0,21873.0,10.66,18.04,320.60,301.20,1.98,72.63
40,meps,SEX,dt,51.5,1442.4,9102.0,161681.0,527.0,5061.0,5.83,3.13,326.53,300.78,1.62,16.83
41,meps,SEX,lr,176.4,1307.8,5847.0,130760.0,791.0,22816.0,13.41,17.42,321.01,300.86,2.46,75.83
42,meps,SEX,mlp,192.9,1297.2,5336.0,106965.0,778.0,15419.0,14.55,14.42,337.92,301.07,2.30,51.21
43,meps,SEX,rf,242.4,1242.0,4805.0,116069.0,846.0,23903.0,17.87,20.59,344.57,301.14,2.47,79.37

In [88]:
classifiers = pivot_df['classifier_name'].unique()
for classifier in classifiers:
    pivot_df[(pivot_df['classifier_name']==classifier)].to_csv(f'{compilation_path}{classifier}_results.csv', index=False)

In [89]:
# avg_results[(avg_results['sensitive_name'] == 'age') & (avg_results['classifier_name'] == 'dt') & (avg_results['dataset_name'] == 'credit')]